export enum SLICES {
  GLOBAL_SLICE = "GLOBAL_SLICE",
  USER_SLICE = "USER_SLICE",
  CARB_CODING_SLICE = "CARB_CODING_SLICE",
  CLIENT_SLICE = "CLIENT_SLICE",
  NOTES_SLICE = "NOTES_SLICE",
  FOOD_LOGS_SLICE = "FOOD_LOGS_SLICE",
  GROUP_SLICE = "GROUP_SLICE",
}
