version: "3"

services:
  coach-desktop:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    command: sleep infinity
    volumes:
      - ../..:/workspaces:cached
    environment:
      ENV_VAR: example
